export const PRODUCTS_LOAD = "PRODUCTS_LOAD";
export const PRODUCTS_LOAD_SUCCESS = "PRODUCTS_LOAD_SUCCESS";
export const PRODUCTS_LOAD_FAILURE = "PRODUCTS_LOAD_FAILURE";
export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
